//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.15 at 08:50:30 AM IST 
//


package com.clicksmob.sdk.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.clicksmob.sdk.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.clicksmob.sdk.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Offers }
     * 
     */
    public Offers createOffers() {
        return new Offers();
    }

    /**
     * Create an instance of {@link Offers.Offer }
     * 
     */
    public Offers.Offer createOffersOffer() {
        return new Offers.Offer();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferCaps }
     * 
     */
    public Offers.Offer.OfferCaps createOffersOfferOfferCaps() {
        return new Offers.Offer.OfferCaps();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferPayouts }
     * 
     */
    public Offers.Offer.OfferPayouts createOffersOfferOfferPayouts() {
        return new Offers.Offer.OfferPayouts();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferTargets }
     * 
     */
    public Offers.Offer.OfferTargets createOffersOfferOfferTargets() {
        return new Offers.Offer.OfferTargets();
    }

    /**
     * Create an instance of {@link CountryList }
     * 
     */
    public CountryList createCountryList() {
        return new CountryList();
    }

    /**
     * Create an instance of {@link PlatformList }
     * 
     */
    public PlatformList createPlatformList() {
        return new PlatformList();
    }

    /**
     * Create an instance of {@link Offers.Offer.Categories }
     * 
     */
    public Offers.Offer.Categories createOffersOfferCategories() {
        return new Offers.Offer.Categories();
    }

    /**
     * Create an instance of {@link Offers.Offer.Android }
     * 
     */
    public Offers.Offer.Android createOffersOfferAndroid() {
        return new Offers.Offer.Android();
    }

    /**
     * Create an instance of {@link Offers.Offer.IOS }
     * 
     */
    public Offers.Offer.IOS createOffersOfferIOS() {
        return new Offers.Offer.IOS();
    }

    /**
     * Create an instance of {@link Offers.Offer.WindowsPhone }
     * 
     */
    public Offers.Offer.WindowsPhone createOffersOfferWindowsPhone() {
        return new Offers.Offer.WindowsPhone();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferCaps.CountryPlatformSet }
     * 
     */
    public Offers.Offer.OfferCaps.CountryPlatformSet createOffersOfferOfferCapsCountryPlatformSet() {
        return new Offers.Offer.OfferCaps.CountryPlatformSet();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferPayouts.OfferPayout }
     * 
     */
    public Offers.Offer.OfferPayouts.OfferPayout createOffersOfferOfferPayoutsOfferPayout() {
        return new Offers.Offer.OfferPayouts.OfferPayout();
    }

    /**
     * Create an instance of {@link Offers.Offer.OfferTargets.OfferTarget }
     * 
     */
    public Offers.Offer.OfferTargets.OfferTarget createOffersOfferOfferTargetsOfferTarget() {
        return new Offers.Offer.OfferTargets.OfferTarget();
    }

}
