//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.15 at 08:50:30 AM IST 
//


package com.clicksmob.sdk.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Offer" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="OfferName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SubHeadline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Categories">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ConversionMode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CPC"/>
 *                         &lt;enumeration value="CPI"/>
 *                         &lt;enumeration value="CPA"/>
 *                         &lt;enumeration value="CPA"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ConversionUserFlow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Restrictions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AndroidPackageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="iOSBundleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AdultTraffic" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="IncentiveAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="MediabuyerAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="KeyworderAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="PushAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="ApplicationTrafficAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="PublisherValidationAutomatic" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="AllowedUseOwnCreative" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="AllowedCustomizeBannerTarget" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="EachCreativeMustHaveDifferentLink" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="ApprovalRequired" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="NeedAcceptTerms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="AllowedWiFi" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="Allowed3G" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="MinimalAge">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RebrokerAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="SMSAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="DiscoveryAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="EmailingAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                   &lt;element name="BannersURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TargetURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ThumbnailURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Android">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AndroidMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AndroidMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isAPK" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="iOS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="iOSMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="iOSMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="WindowsPhone">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="WindowsPhoneMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="WindowsPhoneMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OfferTargets">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OfferTarget" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AndroidPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="iPadPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="iPhonePreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="iPodPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="OtherPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OfferPayouts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OfferPayout" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Payout" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
 *                                       &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OfferCaps">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NoDailyCap" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
 *                             &lt;element name="TotalCapLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="CountryPlatformSet" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
 *                                       &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
 *                                       &lt;element name="DailyCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offer"
})
@XmlRootElement(name = "Offers")
public class Offers {

    @XmlElement(name = "Offer", required = true)
    protected List<Offers.Offer> offer;

    /**
     * Gets the value of the offer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Offers.Offer }
     * 
     * 
     */
    public List<Offers.Offer> getOffer() {
        if (offer == null) {
            offer = new ArrayList<Offers.Offer>();
        }
        return this.offer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OfferName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SubHeadline" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Categories">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ConversionMode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CPC"/>
     *               &lt;enumeration value="CPI"/>
     *               &lt;enumeration value="CPA"/>
     *               &lt;enumeration value="CPA"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ConversionUserFlow" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Restrictions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AndroidPackageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="iOSBundleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AdultTraffic" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="IncentiveAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="MediabuyerAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="KeyworderAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="PushAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="ApplicationTrafficAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="PublisherValidationAutomatic" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="AllowedUseOwnCreative" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="AllowedCustomizeBannerTarget" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="EachCreativeMustHaveDifferentLink" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="ApprovalRequired" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="NeedAcceptTerms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="AllowedWiFi" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="Allowed3G" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="MinimalAge">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RebrokerAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="SMSAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="DiscoveryAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="EmailingAllowed" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *         &lt;element name="BannersURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TargetURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ThumbnailURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Android">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AndroidMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AndroidMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="isAPK" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="iOS">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="iOSMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="iOSMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="WindowsPhone">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="WindowsPhoneMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="WindowsPhoneMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OfferTargets">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OfferTarget" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AndroidPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="iPadPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="iPhonePreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="iPodPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="OtherPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OfferPayouts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OfferPayout" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Payout" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
     *                             &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OfferCaps">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NoDailyCap" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
     *                   &lt;element name="TotalCapLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="CountryPlatformSet" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
     *                             &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
     *                             &lt;element name="DailyCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "offerName",
        "subHeadline",
        "description",
        "categories",
        "conversionMode",
        "conversionUserFlow",
        "restrictions",
        "notes",
        "androidPackageName",
        "iosBundleID",
        "adultTraffic",
        "incentiveAllowed",
        "mediabuyerAllowed",
        "keyworderAllowed",
        "pushAllowed",
        "applicationTrafficAllowed",
        "publisherValidationAutomatic",
        "allowedUseOwnCreative",
        "allowedCustomizeBannerTarget",
        "eachCreativeMustHaveDifferentLink",
        "approvalRequired",
        "needAcceptTerms",
        "allowedWiFi",
        "allowed3G",
        "minimalAge",
        "rebrokerAllowed",
        "smsAllowed",
        "discoveryAllowed",
        "emailingAllowed",
        "bannersURL",
        "targetURL",
        "thumbnailURL",
        "android",
        "ios",
        "windowsPhone",
        "offerTargets",
        "offerPayouts",
        "offerCaps"
    })
    public static class Offer {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "OfferName", required = true)
        protected String offerName;
        @XmlElement(name = "SubHeadline", required = true)
        protected String subHeadline;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Categories", required = true)
        protected Offers.Offer.Categories categories;
        @XmlElement(name = "ConversionMode", required = true)
        protected String conversionMode;
        @XmlElement(name = "ConversionUserFlow", required = true)
        protected String conversionUserFlow;
        @XmlElement(name = "Restrictions", required = true)
        protected String restrictions;
        @XmlElement(name = "Notes", required = true)
        protected String notes;
        @XmlElement(name = "AndroidPackageName", required = true)
        protected String androidPackageName;
        @XmlElement(name = "iOSBundleID", required = true)
        protected String iosBundleID;
        @XmlElement(name = "AdultTraffic")
        protected int adultTraffic;
        @XmlElement(name = "IncentiveAllowed")
        protected int incentiveAllowed;
        @XmlElement(name = "MediabuyerAllowed")
        protected int mediabuyerAllowed;
        @XmlElement(name = "KeyworderAllowed")
        protected int keyworderAllowed;
        @XmlElement(name = "PushAllowed")
        protected int pushAllowed;
        @XmlElement(name = "ApplicationTrafficAllowed")
        protected int applicationTrafficAllowed;
        @XmlElement(name = "PublisherValidationAutomatic")
        protected int publisherValidationAutomatic;
        @XmlElement(name = "AllowedUseOwnCreative")
        protected int allowedUseOwnCreative;
        @XmlElement(name = "AllowedCustomizeBannerTarget")
        protected int allowedCustomizeBannerTarget;
        @XmlElement(name = "EachCreativeMustHaveDifferentLink")
        protected int eachCreativeMustHaveDifferentLink;
        @XmlElement(name = "ApprovalRequired")
        protected int approvalRequired;
        @XmlElement(name = "NeedAcceptTerms")
        protected int needAcceptTerms;
        @XmlElement(name = "AllowedWiFi")
        protected int allowedWiFi;
        @XmlElement(name = "Allowed3G")
        protected int allowed3G;
        @XmlElement(name = "MinimalAge")
        protected int minimalAge;
        @XmlElement(name = "RebrokerAllowed")
        protected int rebrokerAllowed;
        @XmlElement(name = "SMSAllowed")
        protected int smsAllowed;
        @XmlElement(name = "DiscoveryAllowed")
        protected int discoveryAllowed;
        @XmlElement(name = "EmailingAllowed")
        protected int emailingAllowed;
        @XmlElement(name = "BannersURL", required = true)
        protected String bannersURL;
        @XmlElement(name = "TargetURL", required = true)
        protected String targetURL;
        @XmlElement(name = "ThumbnailURL", required = true)
        protected String thumbnailURL;
        @XmlElement(name = "Android", required = true)
        protected Offers.Offer.Android android;
        @XmlElement(name = "iOS", required = true)
        protected Offers.Offer.IOS ios;
        @XmlElement(name = "WindowsPhone", required = true)
        protected Offers.Offer.WindowsPhone windowsPhone;
        @XmlElement(name = "OfferTargets", required = true)
        protected Offers.Offer.OfferTargets offerTargets;
        @XmlElement(name = "OfferPayouts", required = true)
        protected Offers.Offer.OfferPayouts offerPayouts;
        @XmlElement(name = "OfferCaps", required = true)
        protected Offers.Offer.OfferCaps offerCaps;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the offerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOfferName() {
            return offerName;
        }

        /**
         * Sets the value of the offerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOfferName(String value) {
            this.offerName = value;
        }

        /**
         * Gets the value of the subHeadline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubHeadline() {
            return subHeadline;
        }

        /**
         * Sets the value of the subHeadline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubHeadline(String value) {
            this.subHeadline = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the categories property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.Categories }
         *     
         */
        public Offers.Offer.Categories getCategories() {
            return categories;
        }

        /**
         * Sets the value of the categories property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.Categories }
         *     
         */
        public void setCategories(Offers.Offer.Categories value) {
            this.categories = value;
        }

        /**
         * Gets the value of the conversionMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConversionMode() {
            return conversionMode;
        }

        /**
         * Sets the value of the conversionMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConversionMode(String value) {
            this.conversionMode = value;
        }

        /**
         * Gets the value of the conversionUserFlow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConversionUserFlow() {
            return conversionUserFlow;
        }

        /**
         * Sets the value of the conversionUserFlow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConversionUserFlow(String value) {
            this.conversionUserFlow = value;
        }

        /**
         * Gets the value of the restrictions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRestrictions() {
            return restrictions;
        }

        /**
         * Sets the value of the restrictions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRestrictions(String value) {
            this.restrictions = value;
        }

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

        /**
         * Gets the value of the androidPackageName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAndroidPackageName() {
            return androidPackageName;
        }

        /**
         * Sets the value of the androidPackageName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAndroidPackageName(String value) {
            this.androidPackageName = value;
        }

        /**
         * Gets the value of the iosBundleID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIOSBundleID() {
            return iosBundleID;
        }

        /**
         * Sets the value of the iosBundleID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIOSBundleID(String value) {
            this.iosBundleID = value;
        }

        /**
         * Gets the value of the adultTraffic property.
         * 
         */
        public int getAdultTraffic() {
            return adultTraffic;
        }

        /**
         * Sets the value of the adultTraffic property.
         * 
         */
        public void setAdultTraffic(int value) {
            this.adultTraffic = value;
        }

        /**
         * Gets the value of the incentiveAllowed property.
         * 
         */
        public int getIncentiveAllowed() {
            return incentiveAllowed;
        }

        /**
         * Sets the value of the incentiveAllowed property.
         * 
         */
        public void setIncentiveAllowed(int value) {
            this.incentiveAllowed = value;
        }

        /**
         * Gets the value of the mediabuyerAllowed property.
         * 
         */
        public int getMediabuyerAllowed() {
            return mediabuyerAllowed;
        }

        /**
         * Sets the value of the mediabuyerAllowed property.
         * 
         */
        public void setMediabuyerAllowed(int value) {
            this.mediabuyerAllowed = value;
        }

        /**
         * Gets the value of the keyworderAllowed property.
         * 
         */
        public int getKeyworderAllowed() {
            return keyworderAllowed;
        }

        /**
         * Sets the value of the keyworderAllowed property.
         * 
         */
        public void setKeyworderAllowed(int value) {
            this.keyworderAllowed = value;
        }

        /**
         * Gets the value of the pushAllowed property.
         * 
         */
        public int getPushAllowed() {
            return pushAllowed;
        }

        /**
         * Sets the value of the pushAllowed property.
         * 
         */
        public void setPushAllowed(int value) {
            this.pushAllowed = value;
        }

        /**
         * Gets the value of the applicationTrafficAllowed property.
         * 
         */
        public int getApplicationTrafficAllowed() {
            return applicationTrafficAllowed;
        }

        /**
         * Sets the value of the applicationTrafficAllowed property.
         * 
         */
        public void setApplicationTrafficAllowed(int value) {
            this.applicationTrafficAllowed = value;
        }

        /**
         * Gets the value of the publisherValidationAutomatic property.
         * 
         */
        public int getPublisherValidationAutomatic() {
            return publisherValidationAutomatic;
        }

        /**
         * Sets the value of the publisherValidationAutomatic property.
         * 
         */
        public void setPublisherValidationAutomatic(int value) {
            this.publisherValidationAutomatic = value;
        }

        /**
         * Gets the value of the allowedUseOwnCreative property.
         * 
         */
        public int getAllowedUseOwnCreative() {
            return allowedUseOwnCreative;
        }

        /**
         * Sets the value of the allowedUseOwnCreative property.
         * 
         */
        public void setAllowedUseOwnCreative(int value) {
            this.allowedUseOwnCreative = value;
        }

        /**
         * Gets the value of the allowedCustomizeBannerTarget property.
         * 
         */
        public int getAllowedCustomizeBannerTarget() {
            return allowedCustomizeBannerTarget;
        }

        /**
         * Sets the value of the allowedCustomizeBannerTarget property.
         * 
         */
        public void setAllowedCustomizeBannerTarget(int value) {
            this.allowedCustomizeBannerTarget = value;
        }

        /**
         * Gets the value of the eachCreativeMustHaveDifferentLink property.
         * 
         */
        public int getEachCreativeMustHaveDifferentLink() {
            return eachCreativeMustHaveDifferentLink;
        }

        /**
         * Sets the value of the eachCreativeMustHaveDifferentLink property.
         * 
         */
        public void setEachCreativeMustHaveDifferentLink(int value) {
            this.eachCreativeMustHaveDifferentLink = value;
        }

        /**
         * Gets the value of the approvalRequired property.
         * 
         */
        public int getApprovalRequired() {
            return approvalRequired;
        }

        /**
         * Sets the value of the approvalRequired property.
         * 
         */
        public void setApprovalRequired(int value) {
            this.approvalRequired = value;
        }

        /**
         * Gets the value of the needAcceptTerms property.
         * 
         */
        public int getNeedAcceptTerms() {
            return needAcceptTerms;
        }

        /**
         * Sets the value of the needAcceptTerms property.
         * 
         */
        public void setNeedAcceptTerms(int value) {
            this.needAcceptTerms = value;
        }

        /**
         * Gets the value of the allowedWiFi property.
         * 
         */
        public int getAllowedWiFi() {
            return allowedWiFi;
        }

        /**
         * Sets the value of the allowedWiFi property.
         * 
         */
        public void setAllowedWiFi(int value) {
            this.allowedWiFi = value;
        }

        /**
         * Gets the value of the allowed3G property.
         * 
         */
        public int getAllowed3G() {
            return allowed3G;
        }

        /**
         * Sets the value of the allowed3G property.
         * 
         */
        public void setAllowed3G(int value) {
            this.allowed3G = value;
        }

        /**
         * Gets the value of the minimalAge property.
         * 
         */
        public int getMinimalAge() {
            return minimalAge;
        }

        /**
         * Sets the value of the minimalAge property.
         * 
         */
        public void setMinimalAge(int value) {
            this.minimalAge = value;
        }

        /**
         * Gets the value of the rebrokerAllowed property.
         * 
         */
        public int getRebrokerAllowed() {
            return rebrokerAllowed;
        }

        /**
         * Sets the value of the rebrokerAllowed property.
         * 
         */
        public void setRebrokerAllowed(int value) {
            this.rebrokerAllowed = value;
        }

        /**
         * Gets the value of the smsAllowed property.
         * 
         */
        public int getSMSAllowed() {
            return smsAllowed;
        }

        /**
         * Sets the value of the smsAllowed property.
         * 
         */
        public void setSMSAllowed(int value) {
            this.smsAllowed = value;
        }

        /**
         * Gets the value of the discoveryAllowed property.
         * 
         */
        public int getDiscoveryAllowed() {
            return discoveryAllowed;
        }

        /**
         * Sets the value of the discoveryAllowed property.
         * 
         */
        public void setDiscoveryAllowed(int value) {
            this.discoveryAllowed = value;
        }

        /**
         * Gets the value of the emailingAllowed property.
         * 
         */
        public int getEmailingAllowed() {
            return emailingAllowed;
        }

        /**
         * Sets the value of the emailingAllowed property.
         * 
         */
        public void setEmailingAllowed(int value) {
            this.emailingAllowed = value;
        }

        /**
         * Gets the value of the bannersURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersURL() {
            return bannersURL;
        }

        /**
         * Sets the value of the bannersURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersURL(String value) {
            this.bannersURL = value;
        }

        /**
         * Gets the value of the targetURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetURL() {
            return targetURL;
        }

        /**
         * Sets the value of the targetURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetURL(String value) {
            this.targetURL = value;
        }

        /**
         * Gets the value of the thumbnailURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThumbnailURL() {
            return thumbnailURL;
        }

        /**
         * Sets the value of the thumbnailURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThumbnailURL(String value) {
            this.thumbnailURL = value;
        }

        /**
         * Gets the value of the android property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.Android }
         *     
         */
        public Offers.Offer.Android getAndroid() {
            return android;
        }

        /**
         * Sets the value of the android property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.Android }
         *     
         */
        public void setAndroid(Offers.Offer.Android value) {
            this.android = value;
        }

        /**
         * Gets the value of the ios property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.IOS }
         *     
         */
        public Offers.Offer.IOS getIOS() {
            return ios;
        }

        /**
         * Sets the value of the ios property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.IOS }
         *     
         */
        public void setIOS(Offers.Offer.IOS value) {
            this.ios = value;
        }

        /**
         * Gets the value of the windowsPhone property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.WindowsPhone }
         *     
         */
        public Offers.Offer.WindowsPhone getWindowsPhone() {
            return windowsPhone;
        }

        /**
         * Sets the value of the windowsPhone property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.WindowsPhone }
         *     
         */
        public void setWindowsPhone(Offers.Offer.WindowsPhone value) {
            this.windowsPhone = value;
        }

        /**
         * Gets the value of the offerTargets property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.OfferTargets }
         *     
         */
        public Offers.Offer.OfferTargets getOfferTargets() {
            return offerTargets;
        }

        /**
         * Sets the value of the offerTargets property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.OfferTargets }
         *     
         */
        public void setOfferTargets(Offers.Offer.OfferTargets value) {
            this.offerTargets = value;
        }

        /**
         * Gets the value of the offerPayouts property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.OfferPayouts }
         *     
         */
        public Offers.Offer.OfferPayouts getOfferPayouts() {
            return offerPayouts;
        }

        /**
         * Sets the value of the offerPayouts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.OfferPayouts }
         *     
         */
        public void setOfferPayouts(Offers.Offer.OfferPayouts value) {
            this.offerPayouts = value;
        }

        /**
         * Gets the value of the offerCaps property.
         * 
         * @return
         *     possible object is
         *     {@link Offers.Offer.OfferCaps }
         *     
         */
        public Offers.Offer.OfferCaps getOfferCaps() {
            return offerCaps;
        }

        /**
         * Sets the value of the offerCaps property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offers.Offer.OfferCaps }
         *     
         */
        public void setOfferCaps(Offers.Offer.OfferCaps value) {
            this.offerCaps = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AndroidMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AndroidMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="isAPK" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "androidMinimalVersion",
            "androidMaximalVersion",
            "isAPK"
        })
        public static class Android {

            @XmlElement(name = "AndroidMinimalVersion", required = true)
            protected String androidMinimalVersion;
            @XmlElement(name = "AndroidMaximalVersion", required = true)
            protected String androidMaximalVersion;
            protected int isAPK;

            /**
             * Gets the value of the androidMinimalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAndroidMinimalVersion() {
                return androidMinimalVersion;
            }

            /**
             * Sets the value of the androidMinimalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAndroidMinimalVersion(String value) {
                this.androidMinimalVersion = value;
            }

            /**
             * Gets the value of the androidMaximalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAndroidMaximalVersion() {
                return androidMaximalVersion;
            }

            /**
             * Sets the value of the androidMaximalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAndroidMaximalVersion(String value) {
                this.androidMaximalVersion = value;
            }

            /**
             * Gets the value of the isAPK property.
             * 
             */
            public int getIsAPK() {
                return isAPK;
            }

            /**
             * Sets the value of the isAPK property.
             * 
             */
            public void setIsAPK(int value) {
                this.isAPK = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "category"
        })
        public static class Categories {

            @XmlElement(name = "Category", required = true)
            protected List<String> category;

            /**
             * Gets the value of the category property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the category property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCategory().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCategory() {
                if (category == null) {
                    category = new ArrayList<String>();
                }
                return this.category;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="iOSMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="iOSMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "iosMinimalVersion",
            "iosMaximalVersion"
        })
        public static class IOS {

            @XmlElement(name = "iOSMinimalVersion", required = true)
            protected String iosMinimalVersion;
            @XmlElement(name = "iOSMaximalVersion", required = true)
            protected String iosMaximalVersion;

            /**
             * Gets the value of the iosMinimalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIOSMinimalVersion() {
                return iosMinimalVersion;
            }

            /**
             * Sets the value of the iosMinimalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIOSMinimalVersion(String value) {
                this.iosMinimalVersion = value;
            }

            /**
             * Gets the value of the iosMaximalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIOSMaximalVersion() {
                return iosMaximalVersion;
            }

            /**
             * Sets the value of the iosMaximalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIOSMaximalVersion(String value) {
                this.iosMaximalVersion = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NoDailyCap" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}NumericBoolean"/>
         *         &lt;element name="TotalCapLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="CountryPlatformSet" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
         *                   &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
         *                   &lt;element name="DailyCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "noDailyCap",
            "totalCapLimit",
            "countryPlatformSet"
        })
        public static class OfferCaps {

            @XmlElement(name = "NoDailyCap")
            protected int noDailyCap;
            @XmlElement(name = "TotalCapLimit")
            protected Integer totalCapLimit;
            @XmlElement(name = "CountryPlatformSet")
            protected List<Offers.Offer.OfferCaps.CountryPlatformSet> countryPlatformSet;

            /**
             * Gets the value of the noDailyCap property.
             * 
             */
            public int getNoDailyCap() {
                return noDailyCap;
            }

            /**
             * Sets the value of the noDailyCap property.
             * 
             */
            public void setNoDailyCap(int value) {
                this.noDailyCap = value;
            }

            /**
             * Gets the value of the totalCapLimit property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalCapLimit() {
                return totalCapLimit;
            }

            /**
             * Sets the value of the totalCapLimit property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalCapLimit(Integer value) {
                this.totalCapLimit = value;
            }

            /**
             * Gets the value of the countryPlatformSet property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the countryPlatformSet property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCountryPlatformSet().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Offers.Offer.OfferCaps.CountryPlatformSet }
             * 
             * 
             */
            public List<Offers.Offer.OfferCaps.CountryPlatformSet> getCountryPlatformSet() {
                if (countryPlatformSet == null) {
                    countryPlatformSet = new ArrayList<Offers.Offer.OfferCaps.CountryPlatformSet>();
                }
                return this.countryPlatformSet;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
             *         &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
             *         &lt;element name="DailyCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "countries",
                "platforms",
                "dailyCap"
            })
            public static class CountryPlatformSet {

                @XmlElement(name = "Countries", required = true)
                protected CountryList countries;
                @XmlElement(name = "Platforms", required = true)
                protected PlatformList platforms;
                @XmlElement(name = "DailyCap")
                protected int dailyCap;

                /**
                 * Gets the value of the countries property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CountryList }
                 *     
                 */
                public CountryList getCountries() {
                    return countries;
                }

                /**
                 * Sets the value of the countries property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CountryList }
                 *     
                 */
                public void setCountries(CountryList value) {
                    this.countries = value;
                }

                /**
                 * Gets the value of the platforms property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PlatformList }
                 *     
                 */
                public PlatformList getPlatforms() {
                    return platforms;
                }

                /**
                 * Sets the value of the platforms property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PlatformList }
                 *     
                 */
                public void setPlatforms(PlatformList value) {
                    this.platforms = value;
                }

                /**
                 * Gets the value of the dailyCap property.
                 * 
                 */
                public int getDailyCap() {
                    return dailyCap;
                }

                /**
                 * Sets the value of the dailyCap property.
                 * 
                 */
                public void setDailyCap(int value) {
                    this.dailyCap = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OfferPayout" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Payout" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
         *                   &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "offerPayout"
        })
        public static class OfferPayouts {

            @XmlElement(name = "OfferPayout", required = true)
            protected List<Offers.Offer.OfferPayouts.OfferPayout> offerPayout;

            /**
             * Gets the value of the offerPayout property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the offerPayout property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOfferPayout().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Offers.Offer.OfferPayouts.OfferPayout }
             * 
             * 
             */
            public List<Offers.Offer.OfferPayouts.OfferPayout> getOfferPayout() {
                if (offerPayout == null) {
                    offerPayout = new ArrayList<Offers.Offer.OfferPayouts.OfferPayout>();
                }
                return this.offerPayout;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Payout" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="Countries" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}CountryList"/>
             *         &lt;element name="Platforms" type="{http://api.clicksmob.com/xsd/2.0/OffersAPI}PlatformList"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "payout",
                "countries",
                "platforms"
            })
            public static class OfferPayout {

                @XmlElement(name = "Payout")
                protected double payout;
                @XmlElement(name = "Countries", required = true)
                protected CountryList countries;
                @XmlElement(name = "Platforms", required = true)
                protected PlatformList platforms;

                /**
                 * Gets the value of the payout property.
                 * 
                 */
                public double getPayout() {
                    return payout;
                }

                /**
                 * Sets the value of the payout property.
                 * 
                 */
                public void setPayout(double value) {
                    this.payout = value;
                }

                /**
                 * Gets the value of the countries property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CountryList }
                 *     
                 */
                public CountryList getCountries() {
                    return countries;
                }

                /**
                 * Sets the value of the countries property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CountryList }
                 *     
                 */
                public void setCountries(CountryList value) {
                    this.countries = value;
                }

                /**
                 * Gets the value of the platforms property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PlatformList }
                 *     
                 */
                public PlatformList getPlatforms() {
                    return platforms;
                }

                /**
                 * Sets the value of the platforms property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PlatformList }
                 *     
                 */
                public void setPlatforms(PlatformList value) {
                    this.platforms = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OfferTarget" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AndroidPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="iPadPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="iPhonePreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="iPodPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="OtherPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "offerTarget"
        })
        public static class OfferTargets {

            @XmlElement(name = "OfferTarget", required = true)
            protected List<Offers.Offer.OfferTargets.OfferTarget> offerTarget;

            /**
             * Gets the value of the offerTarget property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the offerTarget property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOfferTarget().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Offers.Offer.OfferTargets.OfferTarget }
             * 
             * 
             */
            public List<Offers.Offer.OfferTargets.OfferTarget> getOfferTarget() {
                if (offerTarget == null) {
                    offerTarget = new ArrayList<Offers.Offer.OfferTargets.OfferTarget>();
                }
                return this.offerTarget;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AndroidPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="iPadPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="iPhonePreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="iPodPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="OtherPreviewURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "androidPreviewURL",
                "iPadPreviewURL",
                "iPhonePreviewURL",
                "iPodPreviewURL",
                "otherPreviewURL"
            })
            public static class OfferTarget {

                @XmlElement(name = "AndroidPreviewURL")
                protected String androidPreviewURL;
                protected String iPadPreviewURL;
                protected String iPhonePreviewURL;
                protected String iPodPreviewURL;
                @XmlElement(name = "OtherPreviewURL")
                protected String otherPreviewURL;

                /**
                 * Gets the value of the androidPreviewURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAndroidPreviewURL() {
                    return androidPreviewURL;
                }

                /**
                 * Sets the value of the androidPreviewURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAndroidPreviewURL(String value) {
                    this.androidPreviewURL = value;
                }

                /**
                 * Gets the value of the iPadPreviewURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIPadPreviewURL() {
                    return iPadPreviewURL;
                }

                /**
                 * Sets the value of the iPadPreviewURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIPadPreviewURL(String value) {
                    this.iPadPreviewURL = value;
                }

                /**
                 * Gets the value of the iPhonePreviewURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIPhonePreviewURL() {
                    return iPhonePreviewURL;
                }

                /**
                 * Sets the value of the iPhonePreviewURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIPhonePreviewURL(String value) {
                    this.iPhonePreviewURL = value;
                }

                /**
                 * Gets the value of the iPodPreviewURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIPodPreviewURL() {
                    return iPodPreviewURL;
                }

                /**
                 * Sets the value of the iPodPreviewURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIPodPreviewURL(String value) {
                    this.iPodPreviewURL = value;
                }

                /**
                 * Gets the value of the otherPreviewURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOtherPreviewURL() {
                    return otherPreviewURL;
                }

                /**
                 * Sets the value of the otherPreviewURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOtherPreviewURL(String value) {
                    this.otherPreviewURL = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="WindowsPhoneMinimalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="WindowsPhoneMaximalVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "windowsPhoneMinimalVersion",
            "windowsPhoneMaximalVersion"
        })
        public static class WindowsPhone {

            @XmlElement(name = "WindowsPhoneMinimalVersion", required = true)
            protected String windowsPhoneMinimalVersion;
            @XmlElement(name = "WindowsPhoneMaximalVersion", required = true)
            protected String windowsPhoneMaximalVersion;

            /**
             * Gets the value of the windowsPhoneMinimalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWindowsPhoneMinimalVersion() {
                return windowsPhoneMinimalVersion;
            }

            /**
             * Sets the value of the windowsPhoneMinimalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWindowsPhoneMinimalVersion(String value) {
                this.windowsPhoneMinimalVersion = value;
            }

            /**
             * Gets the value of the windowsPhoneMaximalVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWindowsPhoneMaximalVersion() {
                return windowsPhoneMaximalVersion;
            }

            /**
             * Sets the value of the windowsPhoneMaximalVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWindowsPhoneMaximalVersion(String value) {
                this.windowsPhoneMaximalVersion = value;
            }

        }

    }

}
