//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.15 at 08:50:30 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.clicksmob.com/xsd/2.0/OffersAPI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.clicksmob.sdk.model;
