//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.15 at 08:50:30 AM IST 
//


package com.clicksmob.sdk.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlatformCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlatformCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IPOD"/>
 *     &lt;enumeration value="IPHONE"/>
 *     &lt;enumeration value="IPAD"/>
 *     &lt;enumeration value="ANDROID"/>
 *     &lt;enumeration value="WINDOWSPHONE"/>
 *     &lt;enumeration value="WAP"/>
 *     &lt;enumeration value="BLACKBERRY"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlatformCode")
@XmlEnum
public enum PlatformCode {

    IPOD,
    IPHONE,
    IPAD,
    ANDROID,
    WINDOWSPHONE,
    WAP,
    BLACKBERRY,
    OTHER;

    public String value() {
        return name();
    }

    public static PlatformCode fromValue(String v) {
        return valueOf(v);
    }

}
